#!/usr/bin/env bash
# Purpose: central QIIME2 paths, parameters, filters, resources, optional modules,
#          and automation switches.
# Input: user edits only; sourced by all QIIME2 scripts.
# Output: shell variables, no analysis files.
# Software/resources: none; parameter file only.
#
# Two override layers (both optional, sourced after this file by every script):
#   config.local.sh   - per-project overrides generated by setup_project.sh / run_all.sh
#   work/*.env        - pipeline-generated values (auto metadata path, auto DADA2 params)

# ---------------------------------------------------------------------------
# Conda / environments
# ---------------------------------------------------------------------------
# Set CONDA_SH to the FULL PATH of conda.sh on the SERVER, e.g.
#   /public/home/<user>/anaconda3/etc/profile.d/conda.sh
# (run `conda info --base` on the server, then append /etc/profile.d/conda.sh).
CONDA_SH="/path/to/anaconda3/etc/profile.d/conda.sh"
CONDA_MODULE=""                 # Optional, e.g. miniconda or anaconda; leave empty unless confirmed.
QIIME2_ENV="qiime2"
R_MICROECO_ENV="microeco"      # Separate from QIIME2; must contain R, file2meco, and microeco.
RUN_FILE2MECO_VALIDATION="auto" # yes: require it; no: skip; auto: run only if the env exists.

# ---------------------------------------------------------------------------
# Project paths
# ---------------------------------------------------------------------------
PROJECT_DIR="/path/to/qiime2_project"
FASTQ_DIR="/path/to/fastq"
# Leave METADATA_FILE empty to auto-generate a minimal metadata from sample IDs
# (AUTO_GENERATE_METADATA=yes). Provide a real file to use your own columns.
METADATA_FILE=""
AUTO_GENERATE_METADATA="yes"

# Amplification region, e.g. 16S_V4, 16S_V3V4, ITS1, ITS2, 18S_V4, COI ...
# setup_project.sh / run_all.sh look up primers + expected insert length in
# primers.tsv when REGION is set and the primers below are left empty.
REGION=""

# ---------------------------------------------------------------------------
# Sequencing mode and file naming
# ---------------------------------------------------------------------------
SEQUENCING_MODE="paired"       # paired or single
R1_SUFFIXES=("_R1.fastq.gz" "_R1.fq.gz" ".R1.fastq.gz" ".R1.fq.gz" "_1.fastq.gz" "_1.fq.gz")
R2_SUFFIXES=("_R2.fastq.gz" "_R2.fq.gz" ".R2.fastq.gz" ".R2.fq.gz" "_2.fastq.gz" "_2.fq.gz")
SINGLE_SUFFIXES=(".fastq.gz" ".fq.gz")

# ---------------------------------------------------------------------------
# Classifier
# ---------------------------------------------------------------------------
CLASSIFIER="/path/to/classifier.qza"
# If CLASSIFIER is empty and CLASSIFIER_DIR is set, the pipeline tries to pick a
# classifier whose filename matches the region keywords (primers.tsv) or, if the
# directory contains exactly one .qza, that one.
CLASSIFIER_DIR=""

# ---------------------------------------------------------------------------
# Primer removal (optional)
# ---------------------------------------------------------------------------
# RUN_CUTADAPT: yes -> always run cutadapt; no + AUTO_PRIMER_TRIM=yes -> decide by
# detection; no + AUTO_PRIMER_TRIM=no -> never run cutadapt.
RUN_CUTADAPT="no"
AUTO_PRIMER_TRIM="yes"         # auto-detect primers in reads and trim them when found
FORWARD_PRIMER=""              # filled automatically from REGION if empty
REVERSE_PRIMER=""              # filled automatically from REGION if empty
CUTADAPT_ERROR_RATE="0.1"
CUTADAPT_MINIMUM_LENGTH="1"
CUTADAPT_THREADS="8"

# ---------------------------------------------------------------------------
# DADA2 parameters
# ---------------------------------------------------------------------------
# Manual values win when set. If they are empty and AUTO_TRUNC=yes, the pipeline
# estimates them from the quality profile (bin/estimate_dada2_params.py).
TRIM_LEFT_F=""
TRIM_LEFT_R=""
TRUNC_LEN_F=""
TRUNC_LEN_R=""
AUTO_TRUNC="yes"
QUALITY_THRESHOLD="20"         # mean-Q cutoff used by the auto estimator
MIN_TRUNC_LEN="50"             # never truncate below this many bases
EXPECTED_AMPLICON_LENGTH=""    # insert length WITHOUT primers; from REGION when empty
MAX_ESTIMATOR_SAMPLES="5"      # samples the auto estimator samples
MAX_ESTIMATOR_READS="20000"    # reads per sample the auto estimator samples
DADA2_THREADS="8"
MAX_EE="2.0"                 # DADA2 max expected errors per read (both ends)

# Optional prevalence filter. Empty means no prevalence filtering.
MIN_SAMPLES=""

# ---------------------------------------------------------------------------
# Taxonomy filtering (matching is case-insensitive in q2-taxa)
# ---------------------------------------------------------------------------
TARGET_DOMAIN="Bacteria"       # Bacteria, Archaea, Eukaryota, or empty
EXCLUDE_MITOCHONDRIA="yes"
EXCLUDE_CHLOROPLAST="yes"
EXCLUDE_ARCHAEA="no"           # yes only for a bacteria-only project
EXCLUDE_EUKARYOTA="yes"
EXCLUDE_UNASSIGNED_DOMAIN="no" # yes adds "Unassigned" to the exclude list
CLASSIFIER_JOBS="8"
PHYLOGENY_THREADS="8"

# ---------------------------------------------------------------------------
# Optional QIIME2 downstream summaries
# ---------------------------------------------------------------------------
RUN_CORE_METRICS="no"
SAMPLING_DEPTH=""
RUN_ALPHA_RAREFACTION="no"
ALPHA_MAX_DEPTH=""
RUN_TAXA_BARPLOT="no"

# ---------------------------------------------------------------------------
# Runtime behaviour
# ---------------------------------------------------------------------------
RESUME="yes"                   # yes: skip steps whose outputs already exist
CHECK_GZIP_INTEGRITY="no"      # yes: gzip -t every FASTQ (slow on big data)
COUNT_READS="yes"              # yes: count reads/sample for the QC report
